
spring:
    profiles.active: default
    application:
            name: test-service
server:
    port: 8181

logging:
    level:
      root: INFO

product-service:
  ribbon:
    listOfServers: localhost:8405,localhost:8585

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/